package com.backend.transform.ai.services.senddetails;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.6
 * 2023-08-14T22:48:44.343+05:30
 * Generated source version: 3.5.6
 *
 */
@WebServiceClient(name = "SendDetailsEndpointService",
                  wsdlLocation = "file:/C:/BACKUP/AITransform/send-details-service/src/main/resources/serviceContracts/SoapWSDL/SendDetailsBackend.wsdl",
                  targetNamespace = "http://ai.transform.backend.com/services/senddetails")
public class SendDetailsEndpointService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ai.transform.backend.com/services/senddetails", "SendDetailsEndpointService");
    public final static QName SendDetailsEndpointPort = new QName("http://ai.transform.backend.com/services/senddetails", "SendDetailsEndpointPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/BACKUP/AITransform/send-details-service/src/main/resources/serviceContracts/SoapWSDL/SendDetailsBackend.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SendDetailsEndpointService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/BACKUP/AITransform/send-details-service/src/main/resources/serviceContracts/SoapWSDL/SendDetailsBackend.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SendDetailsEndpointService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SendDetailsEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendDetailsEndpointService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SendDetailsEndpointService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SendDetailsEndpointService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SendDetailsEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SendDetailsEndpoint
     */
    @WebEndpoint(name = "SendDetailsEndpointPort")
    public SendDetailsEndpoint getSendDetailsEndpointPort() {
        return super.getPort(SendDetailsEndpointPort, SendDetailsEndpoint.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendDetailsEndpoint
     */
    @WebEndpoint(name = "SendDetailsEndpointPort")
    public SendDetailsEndpoint getSendDetailsEndpointPort(WebServiceFeature... features) {
        return super.getPort(SendDetailsEndpointPort, SendDetailsEndpoint.class, features);
    }

}
