package com.backend.transform.ai.services.senddetails;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.6
 * 2023-08-14T22:48:44.314+05:30
 * Generated source version: 3.5.6
 *
 */
@WebService(targetNamespace = "http://ai.transform.backend.com/services/senddetails", name = "SendDetailsEndpoint")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SendDetailsEndpoint {

    @WebMethod(operationName = "SendDetails")
    @WebResult(name = "SendDetailsResponse", targetNamespace = "http://ai.transform.backend.com/services/senddetails", partName = "SendDetailsResponse")
    public SendDetailsResponse sendDetails(

        @WebParam(partName = "SendDetailsRequest", name = "SendDetailsRequest", targetNamespace = "http://ai.transform.backend.com/services/senddetails")
        SendDetailsRequest sendDetailsRequest
    );
}
